// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Add Strings
// https://leetcode.com/problems/add-strings/
// 

class Solution {
    public String addStrings(String num1, String num2) {
         StringBuilder sb = new StringBuilder();
        int carry=0;
        int l1=num1.length();
        int l2=num2.length();
        while(l1>0 || l2>0){
            int first = l1>0?Character.getNumericValue(num1.charAt(l1-1)):0;
            int second = l2>0?Character.getNumericValue(num2.charAt(l2-1)):0 ;
            int sum = carry+first+second;
            if(sum>9){
                sum=sum%10;
                carry=1;
            }
            else
                carry=0;
            
            sb.append(sum);
            l1 -= 1;
            l2 -= 1;
        }
        if(carry==1)
            sb.append(1);
        return sb.reverse().toString(); 
    }
}

