// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// String to Integer (atoi)
// https://leetcode.com/problems/string-to-integer-atoi/
// 

class Solution {
    public int myAtoi(String str) {
        if (str == null || str.length() == 0) {
            return 0;
        }
        int result = 0;
        int index = 0;
        int flag = 1;
        while (index <str.length() && str.charAt(index) == ' '){
            index++;
        }
         if (index == str.length() || (str.charAt(index) > '9' && str.charAt(index) < '0')) {
             if (str.charAt(index) == '-') {
                flag = -1;
                 index++;
             } else  if (str.charAt(index) == '+') {
                flag = 1;
                 index++;
             } else 
                 return 0;
         }
        while (index < str.length()) {
            char ch = str.charAt(index);
            if (ch >='0' && ch <= '9') {
                if(result * 10 > Integer.MAX_VALUE) {
                    if (flag == -1) {
                        return Integer.MIN_VALUE;
                    } else {
                        return Integer.MAX_VALUE;
                    }
                }
                result = result* 10 + (int)(ch - '0');
                index++; 
            } 
        }
        return flag * result;
    }
}

