// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// String Compression
// https://leetcode.com/problems/string-compression/
// 

class Solution {
    public int compress(char[] chars) {
        if (chars == null || chars.length == 0) {
            return 0;
        }
        int count = 0;
        int lastIndex = 0;
        int mover  = 0;
        while (mover < chars.length){
            if(chars[mover] == chars[lastIndex]) {
                mover++;
                count++;
            } else {
                 lastIndex++;   
                if (count > 1) {
                    String countSt = String.valueOf(count);
                    for (char ch : countSt.toCharArray()) {
                         chars[lastIndex++] =  ch;
                    }                                  
                }
                
                chars[lastIndex] = chars[mover];
                count = 0;
            }
        }
        if (count > 1) {
            String countSt = String.valueOf(count);
            for (char ch : countSt.toCharArray()) {
                 chars[++lastIndex] =  ch;
            }
        }
        return lastIndex+1;
    }
}

