// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Max Consecutive Ones
// https://leetcode.com/problems/max-consecutive-ones/
// 

class Solution {
    public int findMaxConsecutiveOnes(int[] nums) {
        int left = 0; int right = 0; int max = 0;
        while(right < nums.length) {
            if (nums[right] == 0) {
                max = Math.max(max, right - left);
                left = right + 1;
            }
            right++;
        }
        return max;
    }
}

