// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Merge Two Sorted Lists
// https://leetcode.com/problems/merge-two-sorted-lists/
// 

/**
 * Definition for singly-linked list.
 * public class ListNode {
 *     int val;
 *     ListNode next;
 *     ListNode(int x) { val = x; }
 * }
 */
class Solution {
    public ListNode mergeTwoLists(ListNode l1, ListNode l2) {
          ListNode dummy = new ListNode(0);
        ListNode node =dummy;
        while (l1 != null || l2 != null) {
            if(l1 != null && l2 != null) {
                if(l1.val <= l2.val) {
                    node.next = l1;
                    l1= l1.next;
                } else {
                    node.next = l2;
                    l2= l2.next;
                }
                node = node.next;
            } else {
                if (l1 != null) {
                    node.next = l1;
                } else {
                    node.next = l2;
                }
                break;
            }
        }
        return dummy.next;
    }
}

