// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Convert a Number to Hexadecimal
// https://leetcode.com/problems/convert-a-number-to-hexadecimal/
// 

class Solution {
 /*  Repeat while n != 0:

Step 1: Extract last last four digits of binary verion of the input number n using n & 15
Step 2: Take this as an index and map that to a corresponding hexadecimal-character
Step 3: Shift the input n to the right by 4 bits.
Time complexity: O(1)
Space Complexity: O(1)*/


    public String toHex(int n)
    {
        if(n == 0)
            return "0";
        
        char[] map = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'};
        String result = "";

        while(n != 0)
        {
            result = map[n & 15] + result;
            n >>>= 4;
        }
        return result;
    }

}

