// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Fizz Buzz
// https://leetcode.com/problems/fizz-buzz/
// 

class Solution {
    public List<String> fizzBuzz(int n) {
        List<String> result = new ArrayList<>();
        for (int i = 1; i <= n; i++) {
            if (i % 15 == 0) {
                result.add("FizzBuzz");
            } else if (i % 5 == 0) {
                result.add("Buzz");
            } else if ( i % 3 == 0) {
                result.add("Fizz");
            } else {
                result.add("" + i);
            }
        }
        return result;
    }
}

