# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# Employees Earning More Than Their Managers
# https://leetcode.com/problems/employees-earning-more-than-their-managers/
# 

# Write your MySQL query statement below
select E1.Name  Employee
from Employee as E1, Employee as E2 
where E1.ManagerId = E2.Id and E1.Salary > E2.Salary

