// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Max Consecutive Ones II
// https://leetcode.com/problems/max-consecutive-ones-ii/
// 

class Solution {
    public int findMaxConsecutiveOnes(int[] nums) {
        int left = 0;
        int zeros = 0;
        int result = 0;
        for (int right = 0; right< nums.length; right++) {
            if (nums[right] == 0) {
                zeros++;
            }
            while(zeros > 1) {
                if(nums[left] == 0) {
                    zeros--;
                }
                left++;
            }
            result = Math.max(result, right - left + 1);
        }
        return result;
    }
}

