// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Custom Sort String
// https://leetcode.com/problems/custom-sort-string/
// 

class Solution {
    public String customSortString(String S, String T) {
        if (S == null || S.length() == 0) {
            return T;
        }
        if(T == null || T.length() == 0) {
            return T;
        }
        int[] countT = new int[26];
        for(char ch : T.toCharArray()) {
                countT[ch-'a']++;
        }
        StringBuilder sb = new StringBuilder();
        for (char ch: S.toCharArray()) {
            if (countT[ch - 'a'] > 0) {
                for(int i = 0; i < countT[ch-'a']; i++) {
                    sb.append(ch);
                }
            }
            countT[ch - 'a'] = 0;
        }
        
        for(int i = 0; i < 26; i++) {
            if(countT[i] > 0) {
                char ch = (char)(i + 'a');
                for(int j = 0; j < countT[i]; j++) {
                    sb.append(ch);
                }
            }
        }
        return sb.toString();
    }
}

