// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Merge Sorted Array
// https://leetcode.com/problems/merge-sorted-array/
// 

class Solution {
    public void merge(int[] nums1, int m, int[] nums2, int n) {
        int target = m + n - 1;
        int index1 = m -1;
        int index2 = n -1;
        while (index1 >= 0 || index2 >= 0) {
            if ( index1 >= 0 && index2 >= 0) {
                if (nums1[index1] > nums2[index2]) {
                    nums1[target--] = nums1[index1--];
                } else if (nums1[index1] == nums2[index2]) {
                     nums1[target--] = nums1[index1--];
                     nums1[target--] = nums2[index2--];
                } else {
                    nums1[target--] = nums2[index2--];
                }
            }else {
                while (index2 >=0) {
                     nums1[target--] = nums2[index2--];
                }
                break;
            }
        }
    }
}

