// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Balanced Binary Tree
// https://leetcode.com/problems/balanced-binary-tree/
// 

/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode(int x) { val = x; }
 * }
 */
class Solution {
    public boolean isBalanced(TreeNode root) {
        if (root  == null) { 
            return true;
        }
        int leftH = getHeight(root.left);
        int rightH = getHeight(root.right);
        return isBalanced(root.left) && isBalanced(root.right) && Math.abs(leftH - rightH) <= 1;
    }
    public int getHeight(TreeNode root) {
        if (root == null) {
            return 0;
        }
        return 1 + Math.max(getHeight(root.left), getHeight(root.right));
    }
}

