// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Missing Number
// https://leetcode.com/problems/missing-number/
// 

class Solution {
    public int missingNumber(int[] nums) {
        if (nums == null || nums.length == 0) {
            return 0;
        }
        int missing = nums.length;
        for (int i = 0; i < nums.length; i++) {
            missing += i - nums[i] ;
        }
        return missing;
    }
}

