// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Plus One
// https://leetcode.com/problems/plus-one/
// 

class Solution {
    public int[] plusOne(int[] digits) {
        if (digits == null || digits.length == 0) {
                return digits;
        }
 
    int index = digits.length - 1;
    int carry = 0;
    while (index >= 0) {
        if (digits[index] != 9) {
            digits[index] += 1;
            return digits;
        }
        carry = 1;
        digits[index] = 0;
        index--;
    }
    if (carry  == 1) {
        int[] result = new int[digits.length + 1];
        result[0] = 1;
        return result;
    }
  return null;  
}
}

