// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Reverse Words in a String
// https://leetcode.com/problems/reverse-words-in-a-string/
// 

class Solution {
    public String reverseWords(String s) {
      if (s == null || s.length() == 0) {
           return s;
       }
        
       char[] chars = s.trim().toCharArray();
       reverse(chars, 0 , chars.length - 1);
       int start = 0;
       int end = 0;
       while(end < chars.length) {
          if(chars[end] == ' ') { 
            reverse(chars, start, end - 1);
            end++;
            start = end;                 
          } else {
            end++;
          }
       }
       reverse(chars, start,end - 1);
       StringBuilder sb = new StringBuilder();
        start = 0;  
         while (start < chars.length) {
             sb.append(chars[start]);
             start++;
             if(start < chars.length && chars[start] == ' ') sb.append(' ');
             while(start < chars.length && chars[start] == ' ' ) {
                 start++;
             }
        } 
       return sb.toString().trim();
    }
    
    private void reverse (char[] chars, int start, int end) {
        while(start < end) {
            char tmp = chars[start];
            chars[start] = chars[end];
            chars[end] = tmp;
            start++;
            end--;
        }
    }
}

