// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Reverse Words in a String
// https://leetcode.com/problems/reverse-words-in-a-string/
// 

class Solution {
    public String reverseWords(String s) {
      if (s == null || s.length() < 2) {
           return s;
       }
     
 
		// split to words by space
		String[] arr = s.trim().split(" ");
		StringBuilder sb = new StringBuilder();
		for (int i = arr.length - 1; i >= 0; i--) {
			if (!arr[i].equals("")) {
				sb.append(arr[i]).append(" ");
			}
		}
		//return sb.length() == 0 ? "" : sb.substring(0, sb.length() - 1);
       return sb.toString().trim();
    }
    
    private void reverse (char[] chars, int start, int end) {
        while(start < end) {
            char tmp = chars[start];
            chars[start] = chars[end];
            chars[end] = tmp;
            start++;
            end--;
        }
    }
}

