// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Reverse Linked List
// https://leetcode.com/problems/reverse-linked-list/
// 

/**
 * Definition for singly-linked list.
 * public class ListNode {
 *     int val;
 *     ListNode next;
 *     ListNode(int x) { val = x; }
 * }
 */
class Solution {
    public ListNode reverseList(ListNode head) {
        if (head == null || head.next == null) {
            return head;
        }
        ListNode prev = new ListNode(0);
        prev.next =head;
        ListNode first = head;
        ListNode second = head.next;
        head.next = null;
        while (second != null) {
            first.next = second.next;
            second.next = prev.next;
            prev.next = second;
            second = first.next;
                
        }
        return prev.next;
    }
}

