// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Meeting Rooms
// https://leetcode.com/problems/meeting-rooms/
// 

/**
 * Definition for an interval.
 * public class Interval {
 *     int start;
 *     int end;
 *     Interval() { start = 0; end = 0; }
 *     Interval(int s, int e) { start = s; end = e; }
 * }
 */
class Solution {
    public boolean canAttendMeetings(Interval[] intervals) {
        if (intervals == null || intervals.length <= 1) {
            return true;
        }
        Arrays.sort(intervals, (it1,it2) -> it1.start - it2.start);
        Interval prev = null;
        for (Interval current : intervals) {
            if (prev != null && prev.end > current.start) {
                return false;
            }
            prev = current;
        }
        return true;   
    }
}

