// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Valid Number
// https://leetcode.com/problems/valid-number/
// 

class Solution {
    public boolean isNumber(String s) {
     s = s.trim();
        
        boolean e = false, point = false, num = false, numAfterE = false;
        
        for (int i = 0; i < s.length(); i ++) {
            char ch = s.charAt(i);
            
            if (Character.isDigit(ch)) {
                num = true;
                numAfterE = true;
            } else if (ch == 'e') {
                if (e || !num) return false;
                numAfterE = false;
                e = true;
            } else if (ch == '.') {
                if (point || e) return false;
                point = true;
            } else if (ch == '+' || ch == '-') {
                if (i != 0 && s.charAt(i - 1) != 'e') return false;
            } else return false;
        }
        return num & numAfterE;   
    }
}

