// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Simplify Path
// https://leetcode.com/problems/simplify-path/
// 

class Solution {
    public String simplifyPath(String path) {
       String[] temp = path.split("/");
        int skip = 0;
        String ans = "";
        for(int i = temp.length - 1; i >= 0; i-- ){
            if(temp[i].equals(".") || temp[i].equals(""))
                continue;
            else if(temp[i].equals(".."))
                skip++;
            else if(skip > 0)
                skip--;
            else{
                 ans =  "/" + temp[i]  + ans;
            }
               
        }
        return ans == "" ? "/" :ans; 
    }
}

