// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Spiral Matrix III
// https://leetcode.com/problems/spiral-matrix-iii/
// 

class Solution {
    public int[][] spiralMatrixIII(int R, int C, int r0, int c0) {
         int[][] res = new int[R * C][2];
        res[0] = new int[] {r0, c0};
        int x = 0, y = 1, n = 0, i = 0, tmp, j = 1;
        while (j < R * C) {
            r0 += x; c0 += y; i++;
            if (0 <= r0 && r0 < R && 0 <= c0 && c0 < C)
                res[j++] = new int[] {r0, c0};
            if (i == n / 2 + 1) {
                i = 0; n++; tmp = x; x = y; y = -tmp;
            }
        }
        return res;
    }
}

