// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Verifying an Alien Dictionary
// https://leetcode.com/problems/verifying-an-alien-dictionary/
// 

class Solution {
    public boolean isAlienSorted(String[] words, String order) {
    if (words == null || words.length < 2) {
        return false;
    }
        int index = 0; 
        for (int i = 0; i < words.length - 1; i++) {
            String word1 = words[i];
            String word2 = words[i+1];
            index = 0;
            while (index < Math.min(word1.length(), word2.length())) {
                char ch1 = word1.charAt(index);
                char ch2 = word2.charAt(index);
                if (order.indexOf(ch1) > order.indexOf(ch2)) {
                    return false;
                }else if (order.indexOf(ch1) == order.indexOf(ch2)){
                    index++; 
                } else {
                    break;
                }
            }
            if (index == word2.length() && index < word1.length()) {
                return false;
            }
        }
        return true;
    }
}

