// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Goat Latin
// https://leetcode.com/problems/goat-latin/
// 

class Solution {
    public String toGoatLatin(String S) {
      String[] T=S.split(" ");
    StringBuffer res=new StringBuffer();
    for(int i=0;i<T.length;i++){
        String K=T[i];
        if(K.toLowerCase().charAt(0)== 'a' ||
          K.toLowerCase().charAt(0)==  'e' ||
          K.toLowerCase().charAt(0)==  'i' ||
          K.toLowerCase().charAt(0)==  'o' ||
          K.toLowerCase().charAt(0)==  'u'){
            res.append(K);
            res.append("ma");
        }else{
            res.append(K.substring(1,K.length()));
            res.append(K.substring(0,1));
            res.append("ma");
        }
        for(int j=0;j<i+1;j++){
            res.append("a");
        }
    res.append(" ");
    }
    return res.toString().trim();  
    }
}

