// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Remove Element
// https://leetcode.com/problems/remove-element/
// 

class Solution {
    public int removeElement(int[] nums, int val) {
        int lastIndex = 0;
        int mover = 0;
        while(mover < nums.length) {
             if (nums[mover] != val) {
                nums[lastIndex] = nums[mover];
                lastIndex++;
            }
            mover++;
        }
        return lastIndex;
    }
}

