// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Read N Characters Given Read4
// https://leetcode.com/problems/read-n-characters-given-read4/
// 

/**
 * The read4 API is defined in the parent class Reader4.
 *     int read4(char[] buf);
 */
public class Solution extends Reader4 {
    /**
     * @param buf Destination buffer
     * @param n   Number of characters to read
     * @return    The number of actual characters read
     */
    public int read(char[] buf, int n) {
        int total = 0;
        boolean isEnd = false;
        while(!isEnd && total < n) {
            int tmp = read4(buf);
            total += tmp;
            if(tmp < 4) {
                isEnd = true;
            }
        }
        return total;
    }
}

