// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Island Perimeter
// https://leetcode.com/problems/island-perimeter/
// 

class Solution {
    public int islandPerimeter(int[][] grid) {
        if (grid == null || grid.length ==0 || grid[0].length == 0) {
            return 0;
        }
        int perim = 0;
        for(int i = 0; i < grid.length; i++) {
            for (int j = 0; j < grid[0].length; j++) {
                if (grid[i][j] == 1) {
                    int curPerim = 4;
                    if( i > 0 && grid[i-1][j] == 1) {
                        curPerim--;
                    }
                    if(i < grid.length - 1 && grid[i+1][j] == 1) {
                        curPerim--;
                    }
                    if(j > 0 && grid[i][j-1] == 1) {
                        curPerim--;
                    }
                    if (j < grid[0].length - 1 && grid[i][j+1] == 1) {
                        curPerim--;
                    }
                    perim += curPerim;
                }
            }
        }
        return perim;
    }
}

