// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Sort Colors
// https://leetcode.com/problems/sort-colors/
// 

class Solution {
    public void sortColors(int[] nums) {
       // [0 ... i-1] contains 0
    // [j+1 ... N-1] contains 2
    // [i ... j] contains others
    
       int i = 0;
        int j = nums.length - 1;
        int k = 0;
        
        while (k <= j) {
            if (nums[k] == 0) {
                swap(nums, i, k);
                i++;
                k++;
            } else if (nums[k] == 2) {
                swap(nums, j, k);
                j--;
            } else {
                k++;
            }
        }
    }
    
    private void swap(int[] nums, int i, int j) {
        int temp = nums[i];
        nums[i] = nums[j];
        nums[j] = temp;
    }
}

