// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Inorder Successor in BST
// https://leetcode.com/problems/inorder-successor-in-bst/
// 

/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode(int x) { val = x; }
 * }
 */
class Solution {
    public TreeNode inorderSuccessor(TreeNode root, TreeNode p) {
       if (root == null)
        return null;

      if (root.val <= p.val) {
        return inorderSuccessor(root.right, p);
      } else {
        TreeNode left = inorderSuccessor(root.left, p);
        return (left != null) ? left : root;
      } 
    }
}

