// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Find First and Last Position of Element in Sorted Array
// https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/
// 

class Solution {
    public int[] searchRange(int[] nums, int target) {
        int s = find(nums, target);
        if(s == nums.length || nums[s] != target) {
            return new int[]{-1, -1};
        }
        int e = find(nums, target + 1) - 1;
        if(e == nums.length || nums[e] != target) {
            return new int[]{-1, -1};
        }   
        return new int[]{s, e};
    }
    
    private int find(int[] nums, int target){
        int s = 0, e = nums.length;
        while(s < e){
            int m = (s + e) / 2;
            if(nums[m] >= target) {
                e = m;
            } else {
                s = m + 1;
            }
        }
        return s;
    }
}

