// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Find Peak Element
// https://leetcode.com/problems/find-peak-element/
// 

class Solution {
    public int findPeakElement(int[] nums) {
       if(nums == null || nums.length <= 1) return 0;
        int low = 0;
        int high = nums.length - 1;
        while(low + 1 < high) {
         int mid = high - (high - low) / 2;
         if(nums[mid] > nums[mid + 1] && nums[mid] > nums[mid - 1]) {
             return mid;
         }
            if(nums[mid] < nums[mid - 1]) {
                high = mid;
            } else {
               low = mid ;
            }
         
        }
        if (nums[high] > nums[low]) {
            return high;
        }
        return low;  
    }
}

