// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// First Unique Character in a String
// https://leetcode.com/problems/first-unique-character-in-a-string/
// 

class Solution {
    public int firstUniqChar(String s) {
        int[] indcis = new int[26];
        if (s == null || s.length() == 0) {
            return -1;
        }
        for(int i = 0; i < s.length(); i++) {
            char ch = s.charAt(i);
            if(indcis[ch - 'a'] > 0 || indcis[ch - 'a'] == -1) {
                indcis[ch - 'a'] = -1;
            } else {
                indcis[ch - 'a'] = i + 1;
            }
        }
        int minIndex = s.length() + 1;
        for (int index : indcis) {
            if (index > 0) {
                minIndex = Math.min(minIndex, index);
            }
        }
        if (minIndex == s.length() + 1) {
            return -1;
        }
        return minIndex - 1;
    }
}

