// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Single Number
// https://leetcode.com/problems/single-number/
// 

class Solution {
    public int singleNumber(int[] nums) {
        int sn = nums[0];
        for(int i = 1; i < nums.length; i++) {
            sn ^=nums[i];
        }
        return sn;
    }
}

