// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Subsets
// https://leetcode.com/problems/subsets/
// 

class Solution {
    public List<List<Integer>> subsets(int[] nums) {
     List<List<Integer>> result=new ArrayList();
        backtrack(nums,0,result,new ArrayList());
        return result;
    }
    public void backtrack(int[] nums,int start,List<List<Integer>> result,List<Integer> tmp){
        result.add(new ArrayList(tmp));
        for(int i=start;i<nums.length;i++){
            tmp.add(nums[i]);
            backtrack(nums,i+1,result,tmp);
            tmp.remove(tmp.size()-1);
        }
    }
}

