// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Meeting Rooms II
// https://leetcode.com/problems/meeting-rooms-ii/
// 

/**
 * Definition for an interval.
 * public class Interval {
 *     int start;
 *     int end;
 *     Interval() { start = 0; end = 0; }
 *     Interval(int s, int e) { start = s; end = e; }
 * }
 */
class Solution {
    public int minMeetingRooms(Interval[] intervals) {
        if (intervals == null || intervals.length <= 1) {
            return 1;
        }
         Arrays.sort(intervals, (i1,i2) -> i1.start - i2.start);
        PriorityQueue<Interval> pq = new PriorityQueue<>((i1,i2) -> i1.end - i2.end);
        for(Interval it : intervals) {
            if (pq.isEmpty()) {
                pq.offer(it);
            }else if (pq.peek().end  <= it.start) {
                pq.peek().end = it.start;
            } else {
                pq.offer(it);
            }
        }
        return pq.size();
    }
}

