// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Regular Expression Matching
// https://leetcode.com/problems/regular-expression-matching/
// 

class Solution {
    public boolean isMatch(String s, String p) {
        if (p == null || p.length() == 0)

            return (s == null || s.length() == 0);

        if (p.length() == 1 || p.charAt(1) != '*')

            return (s.length() > 0 && (s.charAt(0) == p.charAt(0) || p.charAt(0) == '.') &&

                isMatch(s.substring(1), p.substring(1)));

        return (isMatch(s, p.substring(2)) || 

                (s.length() > 0 && (s.charAt(0) == p.charAt(0) || p.charAt(0) == '.') && isMatch(s.substring(1), p)));
    }
}

