// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Two Sum II - Input array is sorted
// https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/
// 

class Solution {
    public int[] twoSum(int[] numbers, int target) {
     int left = 0, right = numbers.length-1;
    while(left < right) {
        int sum = numbers[left] + numbers[right];
        if(sum == target) {
            return new int[]{left+1, right+1};
        }else if(sum > target) {
            right--;
        } else {
            left++;
        }
    }
    return new int[]{-1,-1};   
    }
}

