// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Valid Parenthesis String
// https://leetcode.com/problems/valid-parenthesis-string/
// 

class Solution {
    public boolean checkValidString(String s) {
        if (s == null || s.length() == 0) {
            return true;
        }
        int left = 0; int right  = s.length() - 1;
        while(left < right) {
            if(isMatch(s.charAt(left),s.charAt(right))) {
                left++;
                right--;
            } else {
                return false;
            }
        }
        if(left == right) {
            return s.charAt(left) == '*';
        }
        return true;
    }
    private boolean isMatch(char left, char right){
        return (left == '(' && right ==')') || (left == '*' && right == '*')  || (left == '*' && right == ')') || (left == '(' && right == '*');
    }
}

