// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Read N Characters Given Read4 II - Call multiple times
// https://leetcode.com/problems/read-n-characters-given-read4-ii-call-multiple-times/
// 

/**
 * The read4 API is defined in the parent class Reader4.
 *     int read4(char[] buf); 
 */
public class Solution extends Reader4 {
    /**
     * @param buf Destination buffer
     * @param n   Number of characters to read
     * @return    The number of actual characters read
     */
     //because it may call multiple times so we need set temp global variables
    char[] temp = new char[4];
    //tempCount: temp array size
    int tempCount = 0;
    //tempPtr: temp array pointer
    int tempPtr = 0;
    
    public int read(char[] buf, int n) {
        int bufCount = 0;
        
        while (bufCount < n) {
            //no remain char in temp, we can read in new char in temp
            if (tempPtr == 0) {
                tempCount = read4(temp);
            }
            while (bufCount < n && tempPtr < tempCount) {
                buf[bufCount++] = temp[tempPtr++];
            }
            //if equals, we say this temp has no remain char
            if(tempPtr == tempCount)
                tempPtr = 0;
            if (tempCount < 4)
                break;
        }
        return bufCount;
    }
}

