// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Strobogrammatic Number
// https://leetcode.com/problems/strobogrammatic-number/
// 

class Solution {
    public boolean isStrobogrammatic(String num) {
    int l = 0, r = num.length() - 1;
        while(l <= r) {
            if(!isMirror(num.charAt(l), num.charAt(r))) return false;
            l++;
            r--;
        }
        return true;
    }
    
    public boolean isMirror(char c1, char c2) {
        if(c1 == c2) {
            return (c1 == '1' || c1 == '8' || c1 == '0');
        } else {
            return ((c1 == '6' && c2 == '9') || (c1 == '9' && c2 == '6'));
        }
    }
}

