// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Longest Consecutive Sequence
// https://leetcode.com/problems/longest-consecutive-sequence/
// 

class Solution {
    public int longestConsecutive(int[] nums) {
        HashSet<Integer> h = new HashSet<>();
        for(int i = 0; i< nums.length; i++)
        {
            h.add(nums[i]);
        }
        int max = 0;
        while(!h.isEmpty())
        {
            int num = h.iterator().next();
            while(h.contains(num-1)) num--;
            int length = 0;
            while(!h.isEmpty() &&h.contains(num)) {
                length++;
                h.remove(num);
                num++;
            }
            max = Math.max(max, length);
        }
        return max; 
    }
}

