// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Max Area of Island
// https://leetcode.com/problems/max-area-of-island/
// 

class Solution {
    public int maxAreaOfIsland(int[][] grid) {
        int max = 0;
        for(int i = 0; i < grid.length; i++) {
            for (int j = 0; j < grid[0].length; j++) {
                if (grid[i][j] == 1) {
                    max =Math.max(max,dfs(grid,i,j,0));
                }
            }
        }
        return max;
    }
    public int dfs(int[][] grid,int row, int col,  int current) {
        grid[row][col] = 0;
        current++;
         if(row >0 && grid[row-1][col] == 1) {
            current = dfs(grid,row-1,col,current);
        }
        if(col >0 && grid[row][col-1] == 1) {
               current =  dfs(grid,row,col-1,current);
            }
        if(row < grid.length - 1 && grid[row+1][col] == 1) {
                current = dfs(grid,row+1,col,current);
            }
        if(col < grid[0].length - 1 && grid[row][col+1] == 1) {
                current = dfs(grid,row,col+1,current);
            }
        return current;

    }
}

