// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Bulls and Cows
// https://leetcode.com/problems/bulls-and-cows/
// 

class Solution {
    public String getHint(String secret, String guess) {
        int totalA = 0;
        int totalB = 0;
        Map<Character, Integer> map = new HashMap<>();
        for(int i = 0; i < secret.length(); i++) {
            char sc = secret.charAt(i);
            char gc = guess.charAt(i);
            if (sc == gc) {
                totalA++;
                continue;
            }
            if(map.containsKey(sc)) {
                if (map.get(sc) < 0) {
                    totalB++;
                }
                map.put(sc, map.get(sc)+1);
            }else {
                map.put(sc,  1);
            }
            if(map.containsKey(gc)) {
                if (map.get(gc) > 0) {
                    totalB++;
                }
                map.put(gc, map.get(gc)-1);
            } else {
               map.put(gc, -1); 
            }
        }
        StringBuilder sb = new StringBuilder();
            sb.append(totalA).append('A');
            sb.append(totalB).append('B');
        
        return sb.toString();
    }
}

