// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Read N Characters Given Read4 II - Call multiple times
// https://leetcode.com/problems/read-n-characters-given-read4-ii-call-multiple-times/
// 

/**
 * The read4 API is defined in the parent class Reader4.
 *     int read4(char[] buf); 
 */
public class Solution extends Reader4 {
   
    /**
     * @param buf Destination buffer
     * @param n   Maximum number of characters to read
     * @return    The number of characters read
     */
    int index = 0;
    int count = 0;
    char[] buffer4 = new char[4];
    public int read(char[] buf, int n) {
        int actRead = 0;
        boolean isEnd = false;
        while(!isEnd && actRead<n)
        {
            if(count == 0)
            {
                count = read4(buffer4);
                if(count<4)
                    isEnd = true;
            }
            while(count>0 && actRead<n)
            {
                buf[actRead] = buffer4[index];
                actRead++;
                index++;
                count--;
                index = index%4;
            }
        }
        return actRead;
    }


}

