// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Decode String
// https://leetcode.com/problems/decode-string/
// 

class Solution {
    int index = 0;
    
    public String decodeString(String s) {
        StringBuilder sb = new StringBuilder();
        int num = 0;
        
        while(index < s.length()) {
            char curr = s.charAt(index);
            index++;
            
            if(Character.isLetter(curr)) {
                sb.append(curr);
            } else if(Character.isDigit(curr)) {
                num *= 10;
                num += (curr - '0');
            } else if(curr == '[') {
                String result = decodeString(s);
                
                for(int i = 0; i < num; i++) sb.append(result);
                num = 0;
            } else if(curr == ']') {
                return sb.toString();
            }
        }
        
        return sb.toString();  
    }
}

