// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Add Binary
// https://leetcode.com/problems/add-binary/
// 

class Solution {
    public String addBinary(String a, String b) {
        StringBuilder sb = new StringBuilder();
        int indexA = a.length() - 1;
        int indexB = b.length() - 1;
        int carry = 0;
        while (indexA >= 0 || indexB >= 0) {
           int sum = carry;
            if (indexA >= 0) {
                sum += a.charAt(indexA) - '0';
                indexA--;
            }
            if (indexB >= 0) {
                sum += b.charAt(indexB) - '0';
                indexB--;
            }
            sb.append(sum % 2);
            carry = sum / 2;            
        }
        if (carry != 0) {
            sb.append(carry);
        }
        return sb.reverse().toString();
    }
}

