// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Word Break
// https://leetcode.com/problems/word-break/
// 

class Solution {
    public boolean wordBreak(String s, List<String> wordDict) {
       if (s == null || s.length() == 0) return false;
  
  int n = s.length();
  
  // dp[i] represents whether s[0...i] can be formed by dict
  boolean[] dp = new boolean[n+1];
  dp[0] = true;
  for (int i = 1; i <= n; i++) {
    for (int j = 0; j < i; j++) {
      String sub = s.substring(j, i);
      
      if (wordDict.contains(sub) && dp[j]) {
        dp[i] = true;
        break;
      }
    }
  }
  
  return dp[n];  
    }
}

