// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Closest Binary Search Tree Value
// https://leetcode.com/problems/closest-binary-search-tree-value/
// 

/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode(int x) { val = x; }
 * }
 */
class Solution {
    public int closestValue(TreeNode root, double target) {
       TreeNode child = target < root.val ? root.left : root.right;
        if (child == null) {
            return root.val; 
        }
        int childClosest = closestValue(child, target);
        return Math.abs(root.val - target) < Math.abs(childClosest - target) ? root.val : childClosest; 
    }
}

