// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Product of Array Except Self
// https://leetcode.com/problems/product-of-array-except-self/
// 

class Solution {
    public int[] productExceptSelf(int[] nums) {
        int n = nums.length;
        int[] sum = new int[n];
        int tmp = 1;
        for (int i = 0; i < n; i++) {
            sum[i] = tmp;
            tmp *= nums[i];
        }
        tmp = 1;
        for (int i = n - 1; i >= 0; i--) {
            sum[i] = sum[i] * tmp;
            tmp *= nums[i];
        }
        return sum;
    }
}

