// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Valid Palindrome
// https://leetcode.com/problems/valid-palindrome/
// 

class Solution {
    public boolean isPalindrome(String s) {
        if (s == null || s.length() <= 1) {
            return true;
        }
        s = s.toLowerCase();
        int left = 0, right = s.length() - 1;
        while(left < right) {
            char lch = s.charAt(left);
            char rch = s.charAt(right);
            if(lch < 'a' || lch > 'z'){
                left++;
            } else if (rch < 'a' || rch > 'z') {
                right--;
            } else if(s.charAt(left) != s.charAt(right)) {
                return false;
            } else {
                left++;
                right--;
            }
        }
        return true;
    }
}

