// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Remove Duplicates from Sorted Array
// https://leetcode.com/problems/remove-duplicates-from-sorted-array/
// 

class Solution {
    public int removeDuplicates(int[] nums) {
       int lastIndex = 0;
        int mover = 0;
        while(mover < nums.length) {
            if (nums[lastIndex] == nums[mover]) {
                mover++;
            } else {
                lastIndex++;
                nums[lastIndex] = nums[mover];
            }
        }
        return lastIndex + 1;
    }
}

