// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Squares of a Sorted Array
// https://leetcode.com/problems/squares-of-a-sorted-array/
// 

class Solution {
    public int[] sortedSquares(int[] A) {
          if (A == null || A.length == 0) {
             return new int[0];
          }  
          int[] result = new int[A.length];
          int right = 0;
          while (right < A.length && A[right] < 0 ) {
            right++;
          } 
          int left = right - 1;
          int index = 0;
          while(left >= 0 && right < A.length) {
            if (A[left] * A[left] <= A[right] * A[right]) {
                result[index] = A[left] * A[left];
                left--;
            } else {
                result[index] = A[right]*A[right];
                right++;
            } 
              index++;
          }
        while(index < A.length && left >= 0) {
            result[index] = A[left] *A[left];
            index++;
            left--;
        }
        while(index < A.length && right < A.length) {
            result[index] = A[right] * A[right];
            index++;
            right++;
        }
        return result;
    }
}

