// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Valid Parentheses
// https://leetcode.com/problems/valid-parentheses/
// 

class Solution {
    public boolean isValid(String s) {
        if (s == null || s.length() == 0) {
            return true;
        }
        if (s.length() == 1) {
            return false;
        }
        Stack<Character> stack = new Stack<>();
        for (char ch : s.toCharArray()) {
             if (ch == '(' || ch == '[' || ch == '{') {
                    stack.push(ch);
             } else {
                if(stack.isEmpty()) {
                    return false;
                }
                 char top = stack.pop();
                 if(!isMatch(top,ch)) {
                     return false;
                 }
             }
        }
        return stack.isEmpty();
    }
    public boolean isMatch(char left, char right) {
        return (left== '(' && right == ')') || (left == '['&& right ==']') || (left == '{'&& right =='}');
    }
}

