// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Kth Smallest Element in a BST
// https://leetcode.com/problems/kth-smallest-element-in-a-bst/
// 

/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode(int x) { val = x; }
 * }
 */
class Solution {
    public int kthSmallest(TreeNode root, int k) {
        TreeNode result = traverse(root, k);
        if (result == null) {
            return -1;
        }
        return result.val;
    }
    TreeNode traverse (TreeNode root, int k) {
        if (root == null) {
            return null;
        }
        TreeNode node = traverse(root.left, k);
        if (node != null) {
            return node;
        }
        k--;
        if (k == 0) {
            return root;
        }
        return traverse(root.right, k);
    }
}

