// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Move Zeroes
// https://leetcode.com/problems/move-zeroes/
// 

class Solution {
    public void moveZeroes(int[] nums) {
        int indexOfZero = 0;
        int len = nums.length;
        int mover = 0;
        while (mover < len) {
            if (nums[mover] != 0) {
                nums[indexOfZero++] = nums[mover++];
            } else {
                mover++;
            }
        }
        while (indexOfZero < len) {
            nums[indexOfZero++] = 0;
        }
            
    }
}

